# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-07-04 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User01',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username01', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=32)),
                ('password01', models.CharField(max_length=32)),
                ('st_number', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=32)),
                ('company', models.CharField(max_length=32)),
                ('class0', models.CharField(max_length=32)),
            ],
        ),
    ]
