# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-07-05 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20200706_0000'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User02',
        ),
        migrations.RenameField(
            model_name='user02',
            old_name='name',
            new_name='username',
        ),
    ]
